server:
  url: http://localhost:{server.port}/music-streamer/v1
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://192.168.0.225:3306/musicStreamer
    username: root
    password: mariadb
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    enabled: true
    locations: src/main/resources/db/migration
    schemas: musicStreamer
    baseline-on-migrate: true
    baseline-version: 1
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    url: jdbc:mysql://localhost:3306/musicStreamer?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    user: root
    password: mariadb
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO

storage:
  music:
    path: C:/streamerAplication/media/music/
    mediaType: .mp3
  image:
    path: C:/streamerAplication/media/image/
    mediaType: .jpg
    url: http://localhost:8081/music-streamer/v1/images/

