name: project cicd flow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mariadb:
        image: vitortenorio/music-db
        env:
          MYSQL_ROOT_PASSWORD: mariadb
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
